(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "pallet")
(depends-on "starter-kit")
(depends-on "starter-kit-lisp")
;; (depends-on "starter-kit-bindings")
;; (depends-on "starter-kit-eshell")
(depends-on "paredit")
(depends-on "markdown-mode")
(depends-on "enh-ruby-mode")
(depends-on "flymake-ruby")
(depends-on "flymake-cursor")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "rainbow-delimiters")
(depends-on "clojure-mode")
(depends-on "imenu-anywhere")
(depends-on "robe")
(depends-on "bundler")
(depends-on "company")
(depends-on "cider")
(depends-on "ag")
(depends-on "soft-morning-theme")
(depends-on "web-mode")
(depends-on "speedbar")
(depends-on "ecb")
(depends-on "evil")
(depends-on "zenburn-theme")
(depends-on "clj-refactor")
(depends-on "slamhound")
(depends-on "multiple-cursors")
(depends-on "android-mode")
(depends-on "command-log-mode")
